// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/notifier.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91b6e59af44fd9d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PostRequestV1 struct {
	SealedAddress        []byte   `protobuf:"bytes,1,opt,name=sealed_address,json=sealedAddress,proto3" json:"sealed_address,omitempty"`
	Contents             []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequestV1) Reset()         { *m = PostRequestV1{} }
func (m *PostRequestV1) String() string { return proto.CompactTextString(m) }
func (*PostRequestV1) ProtoMessage()    {}
func (*PostRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91b6e59af44fd9d, []int{1}
}

func (m *PostRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequestV1.Unmarshal(m, b)
}
func (m *PostRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequestV1.Marshal(b, m, deterministic)
}
func (m *PostRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequestV1.Merge(m, src)
}
func (m *PostRequestV1) XXX_Size() int {
	return xxx_messageInfo_PostRequestV1.Size(m)
}
func (m *PostRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequestV1 proto.InternalMessageInfo

func (m *PostRequestV1) GetSealedAddress() []byte {
	if m != nil {
		return m.SealedAddress
	}
	return nil
}

func (m *PostRequestV1) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type FetchRequest struct {
	DeaddropId           []byte   `protobuf:"bytes,1,opt,name=deaddrop_id,json=deaddropId,proto3" json:"deaddrop_id,omitempty"`
	LastRead             []byte   `protobuf:"bytes,2,opt,name=last_read,json=lastRead,proto3" json:"last_read,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91b6e59af44fd9d, []int{2}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetDeaddropId() []byte {
	if m != nil {
		return m.DeaddropId
	}
	return nil
}

func (m *FetchRequest) GetLastRead() []byte {
	if m != nil {
		return m.LastRead
	}
	return nil
}

type Notification struct {
	Hint                 uint32   `protobuf:"varint,1,opt,name=hint,proto3" json:"hint,omitempty"`
	Contents             []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91b6e59af44fd9d, []int{3}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetHint() uint32 {
	if m != nil {
		return m.Hint
	}
	return 0
}

func (m *Notification) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type FetchResponse struct {
	Notifications        []*Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91b6e59af44fd9d, []int{4}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*PostRequestV1)(nil), "pb.PostRequestV1")
	proto.RegisterType((*FetchRequest)(nil), "pb.FetchRequest")
	proto.RegisterType((*Notification)(nil), "pb.Notification")
	proto.RegisterType((*FetchResponse)(nil), "pb.FetchResponse")
}

func init() { proto.RegisterFile("pb/notifier.proto", fileDescriptor_f91b6e59af44fd9d) }

var fileDescriptor_f91b6e59af44fd9d = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xdb, 0x7e, 0x9f, 0xda, 0x4e, 0xbb, 0x62, 0xe7, 0x54, 0xd6, 0x83, 0xb2, 0x20, 0xf4,
	0xb4, 0xd2, 0x2a, 0x5e, 0x04, 0xc1, 0x83, 0x8a, 0x20, 0x45, 0x72, 0xe8, 0x75, 0xc9, 0x6e, 0x46,
	0xba, 0x50, 0x93, 0xb8, 0x19, 0x0f, 0x1e, 0xfc, 0xdf, 0x25, 0xd9, 0xad, 0xa4, 0x17, 0x6f, 0xc9,
	0xe3, 0xe5, 0x37, 0x6f, 0x5e, 0x60, 0x6a, 0xcb, 0x4b, 0x6d, 0xb8, 0x7e, 0xab, 0xa9, 0xc9, 0x6d,
	0x63, 0xd8, 0xe0, 0xc0, 0x96, 0xd9, 0x11, 0x1c, 0x3c, 0xbc, 0x5b, 0xfe, 0xca, 0x04, 0x24, 0xaf,
	0xc6, 0xb1, 0xa0, 0x8f, 0x4f, 0x72, 0xbc, 0x5e, 0xe0, 0x05, 0x1c, 0x3b, 0x92, 0x5b, 0x52, 0x85,
	0x54, 0xaa, 0x21, 0xe7, 0x66, 0xfd, 0xf3, 0xfe, 0x7c, 0x22, 0x92, 0x56, 0xbd, 0x6f, 0x45, 0x4c,
	0x61, 0x58, 0x19, 0xcd, 0xa4, 0xd9, 0xcd, 0x06, 0xc1, 0xf0, 0x7b, 0xcf, 0x5e, 0x60, 0xf2, 0x48,
	0x5c, 0x6d, 0x3a, 0x28, 0x9e, 0xc1, 0x58, 0x91, 0xa7, 0x19, 0x5b, 0xd4, 0xaa, 0xe3, 0xc1, 0x4e,
	0x7a, 0x56, 0x78, 0x0a, 0xa3, 0xad, 0x74, 0x5c, 0x34, 0x24, 0xd5, 0x8e, 0xe6, 0x05, 0x41, 0x52,
	0x65, 0x77, 0x30, 0x59, 0x85, 0x05, 0x2a, 0xc9, 0xb5, 0xd1, 0x88, 0xf0, 0x7f, 0x53, 0x6b, 0x0e,
	0x98, 0x44, 0x84, 0xf3, 0x9f, 0x69, 0x9e, 0x20, 0xe9, 0xd2, 0x38, 0x6b, 0xb4, 0x23, 0xbc, 0x81,
	0x44, 0x47, 0x40, 0xbf, 0xe0, 0xbf, 0xf9, 0x78, 0x79, 0x92, 0xdb, 0x32, 0x8f, 0x27, 0x89, 0x7d,
	0xdb, 0xf2, 0x1b, 0x86, 0xab, 0xae, 0x49, 0xbc, 0x06, 0xf4, 0xb5, 0xc5, 0xf6, 0xf5, 0x02, 0xa7,
	0x1e, 0xb1, 0x57, 0x67, 0x3a, 0xf2, 0x52, 0x5b, 0x75, 0x0f, 0x6f, 0x01, 0x43, 0x94, 0xf8, 0x99,
	0xc3, 0x30, 0x38, 0x2e, 0x2c, 0x9d, 0x46, 0x4a, 0x1b, 0x3a, 0xeb, 0x95, 0x87, 0xe1, 0xf7, 0xae,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x62, 0x53, 0xad, 0xd2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifierClient interface {
	PostNotificationV1(ctx context.Context, in *PostRequestV1, opts ...grpc.CallOption) (*Empty, error)
	FetchNotifications(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
}

type notifierClient struct {
	cc *grpc.ClientConn
}

func NewNotifierClient(cc *grpc.ClientConn) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) PostNotificationV1(ctx context.Context, in *PostRequestV1, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.Notifier/PostNotificationV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) FetchNotifications(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/pb.Notifier/FetchNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifierServer is the server API for Notifier service.
type NotifierServer interface {
	PostNotificationV1(context.Context, *PostRequestV1) (*Empty, error)
	FetchNotifications(context.Context, *FetchRequest) (*FetchResponse, error)
}

// UnimplementedNotifierServer can be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (*UnimplementedNotifierServer) PostNotificationV1(ctx context.Context, req *PostRequestV1) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostNotificationV1 not implemented")
}
func (*UnimplementedNotifierServer) FetchNotifications(ctx context.Context, req *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNotifications not implemented")
}

func RegisterNotifierServer(s *grpc.Server, srv NotifierServer) {
	s.RegisterService(&_Notifier_serviceDesc, srv)
}

func _Notifier_PostNotificationV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).PostNotificationV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifier/PostNotificationV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).PostNotificationV1(ctx, req.(*PostRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_FetchNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).FetchNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notifier/FetchNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).FetchNotifications(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostNotificationV1",
			Handler:    _Notifier_PostNotificationV1_Handler,
		},
		{
			MethodName: "FetchNotifications",
			Handler:    _Notifier_FetchNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/notifier.proto",
}
